### PR TITLE
Ability to add extensions to compiler

### PR DESCRIPTION
**Pull request by riadloukili**
Ability to add extensions to compiler through extend() method

### CODE REVIEW

**Comment by duncan3dc** [comment]
@riadloukili Thanks :+1:

**Comment by duncan3dc** [comment]
This is available in release [3.1.0](https://github.com/duncan3dc/blade/releases/tag/3.1.0)

**Comment by rafmst** [comment]
Any documentation on how to create new extension? Thanks

**Comment by riadloukili** [comment]
It's as simple as 1-2-3, just checkout this question http://stackoverflow.com/questions/13002626/laravels-blade-how-can-i-set-variables-in-a-template and you'll figure it out.. Basically, call extend method on blade instance. 😅

**Comment by duncan3dc** [comment]
@ptraceur It's often better to use the [directive()](https://laravel.com/docs/5.3/blade#extending-blade) approach to add extra functionality

**Comment by rafmst** [comment]
Thanks to both 😄

**Pull request merged**
